`June 3, 2022`

# Module 2: Python for Data Analysis

# Numpy

**Array:** 
- Tipe data terstruktur yang menyimpan data dengan tipe data yang seragam
- Mutable
- Index dimulai dari 0
- Bisa berbentuk 1D, 2D, 3D, ..., nD

**Dimensi:**
- Jumlah index yang dibutuhkan untuk memanggil suatu elemen
- array 1D punya 1 index --> vector
- array 2D punya 2 index --> matrix
- array 3D punya 2 index --> 3D array
- array nD punya 2 index --> nD array

**Numpy:**
- NumPy --> Numerical Python
- Library python untuk mengelola data array.
- Bisa digunakan untuk operasi matrix, aljabar linear, dan operasi matematika tingkat lanjut.
- Kecepatan operasi dengan array 50 kali lebih cepat daripada list.
- Function untuk NumPy Array lebih banyak untuk pekerjaan data science.

**Persamaan list dengan np.array**
1. Menggunakan []
2. Mutable
3. Can be indexed & sliced

**Perbedaan**
1. Array consumes less memory
2. Array can handle directly math ops
3. Array is faster
4. List can consist of different nested data size
5. List can store different dtypes

In [1]:
# Import numpy library
import numpy as np

## Create Array

In [2]:
# Membuat 1D array dari sebuah List
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)
array_1d

array([1, 2, 3, 4, 5])

In [4]:
import sys

sys.getsizeof(list_1d)

120

In [14]:
array_1d.nbytes

20

In [ ]:
# Membuat 2D array dari sebuah List
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(list_2d)
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Membuat 3D array dari sebuah List
list_3d = [
           [
            [1, 2],
            [3, 4],
            [5, 6]
           ],
           [
            [7, 8],
            [9, 10],
            [11, 12]
           ]
]

array_3d = np.array(list_3d)
array_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
# Array berisi angka berurut menggunakan np.arange()
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=0, stop=11, step=2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# Array berisi hanya angka 0 (np.zeros())

# default output dtype adalah float
x = np.zeros(5, dtype=np.int16) 
print(x)
print(type(x))
print(x.shape)

[0 0 0 0 0]
<class 'numpy.ndarray'>
(5,)


In [ ]:
x = np.zeros((5, 3)) # angka pertama 
                # merepresentasikan baris, 
        # angka kedua merepresentasikan kolom 
print(x)
print(x.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(5, 3)


In [ ]:
# Array berisi angka 1
np.ones(3)

array([1., 1., 1.])

In [ ]:
x = np.ones((3, 3, 3))
print(x)
print(x.shape)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
(3, 3, 3)


In [ ]:
# Array berisi angka 0 dengan angka 1 
    # secara diagonal
# Sebagai identity matrix pada linear algebra
    # when you multiply the identity matrix 
    # with compatible matrix, you get back 
    # the same matrix.
# Compatible matrix means the number of column 
    # in 1st matrix should be equal to the no. 
    # of row in 2nd matrix. 
    # Ex: mat 2x3 * 3*5 = dot product = 2*5

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Array yang membagi sekian elemen 
    # dengan interval yang sama

np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Membuat array berisi angka random

- rand()
- randn()
- randint()

Biasanya digunakan untuk membuat contoh (dummy) dataset.

In [ ]:
# rand() --> Angka berisi angka random 0 - 1 
np.random.rand(5)

array([0.16781474, 0.59476911, 0.45750805, 0.52849216, 0.78077099])

In [ ]:
np.random.rand(2, 5)

array([[0.2873342 , 0.9067604 , 0.1682723 , 0.65227325, 0.28636871],
       [0.91766492, 0.36929593, 0.92541756, 0.20356656, 0.51729742]])

In [ ]:
# randn() --> Array berisi angka random yang mengikuti 
    # pola distribusi normal, dengan rata-rata = 0 
    # dan standar deviasi mendekati 1
np.random.randn(30)

array([ 0.57865264, -1.62028516, -0.31721012, -1.43193514,  1.53565145,
       -2.94058819, -1.47713756, -1.54389412, -1.02394608,  0.07227661,
        0.09163893,  0.33902538, -0.5988163 , -0.87364888, -1.13664412,
       -0.09015759,  0.43603662,  1.90052915,  0.29223785,  0.06284854,
       -0.24187427, -2.89718726, -1.02830353,  0.78886764,  1.14421105,
       -0.79452402, -1.0727334 ,  0.09503987,  0.70193218, -0.27734292])

In [ ]:
# randint() --> Array berisi angka random integer
# batas atas bersifat exclusive (n-1)
    # 1 <= n < 10
np.random.randint(1, 10) 

5

In [ ]:
# Membuat array 2D dengan 2 baris dan 3 kolom 
    # menggunakan randint()
np.random.randint(5, 10, (2, 3))

array([[6, 7, 6],
       [8, 5, 9]])

## Attributes and Methods

In [ ]:
x_1d = np.arange(0, 12)
print(x_1d)
print(x_1d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [ ]:
# reshape dapat digunakan selama jumlah item 
    # sebelum dan sesudah reshape tetap sama
# Mengubah 1d array menjadi 2d array
x_2d = x_1d.reshape(3, 4)
x_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
x_2d.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
x_2d = x.reshape(2, 6)
print(x_2d)
print(x_2d.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [ ]:
# Error karena ada perbedaan size 
#   antara sebelum dan sesudah reshape
x_2d = x.reshape(2, 5)
x_2d

ValueError: ignored

In [ ]:
# Mengubah array nd menjadi array 1D 
    # secara cepat dengan menggunakan .reshape(-1)
x_2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Methods

In [ ]:
arr_rand = np.random.randint(1, 100, 10)
arr_rand

array([ 8, 36, 79, 82, 10, 83, 88, 45, 63,  9])

In [ ]:
# Mencari nilai maksimum pada suatu array
arr_rand.max()

88

In [ ]:
# Mencari nilai minimum pada suatu array
arr_rand.min()

8

In [ ]:
# Mengetahui index dari nilai maksimum 
    # pada suatu array
arr_rand.argmax()

6

In [ ]:
# Mengetahui index dari nilai minimum 
    # pada suatu array
arr_rand.argmin()

0

In [ ]:
# Mengetahui tipe data dari elemen 
    # pada suatu array
arr_rand.dtype

dtype('int64')

In [19]:
# Array structured
# Jika ingin menampung berbeda tipe data
z = np.array([[5, 'saya', 7, 8.5], [1, 2, 3]], 
    dtype='object')
z

array([list([5, 'saya', 7, 8.5]), list([1, 2, 3])], dtype=object)

In [16]:
z.dtype

dtype('O')

In [20]:
z[0][0] = 6
z

array([list([6, 'saya', 7, 8.5]), list([1, 2, 3])], dtype=object)

In [17]:
type(z[0])

tuple

## Indexing

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Indexing 1 element
arr[5]

5

In [ ]:
# Indexing [start:stop:step] urutan maju
arr[0:7:2]

array([0, 2, 4, 6])

In [ ]:
# Indexing [start:stop:step] urutan mundur
arr[8:0:-2]

array([8, 6, 4, 2])

In [ ]:
# Mengganti nilai dari index tertentu
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Slicing

Hati-hati dengan slicing pada array, jika yang di-slice diubah nlainya, maka nilai pada array awal akan ikut berubah.

Solusinya adalah dengan menduplikat array terlebih dahulu dengan menggunakan .copy()

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Slicing array dan simpan pada variabel baru
slice_arr = arr[0:5]
slice_arr

array([0, 1, 2, 3, 4])

In [ ]:
# Mengganti nilai pada seluruh element
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99])

In [ ]:
# Kalau kita panggil lagi arr awal, nilai 
    # pada index 0 sampai 5 akan berubah juga
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# Agar tidak mengubah nilai pada array awal, 
    # gunakan method np.copy()
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr_copy[0:5]
arr_copy

array([99, 99, 99, 99, 99])

In [ ]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100])

In [ ]:
# Nilai pada array awal tidak berubah 
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# Membuat array 2d

arr_2d = np.array([[10, 15, 20], 
[25,30, 35], [40, 45, 50]])
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [ ]:
# Slicing baris index 1
arr_2d[1]

array([25, 30, 35])

In [ ]:
# Slicing baris index 0, lalu 
    # slicing kolom index 1
arr_2d[0][1] # [baris][kolom]

15

In [ ]:
# Slicing baris index 0, lalu 
    # slicing kolom index 1
arr_2d[0, 1] # [baris, kolom]

15

In [ ]:
# Slicing baris index 0 dan 1, 
    # lalu slicing kolom 1 dan 2
arr_2d[:2, 1:]

array([[15, 20],
       [30, 35]])

In [ ]:
# Hati-hati dalam melakukan indexing dengan slicing
# Kalau seperti ini, jadinya slicing baris index [0:2] 
    # terlebih dahulu, lalu slicing index [1:]
arr_2d[:2][:1]

array([[10, 15, 20]])

## Fancy Indexing

In [ ]:
arr = np.arange(0, 1100, 100)
arr

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
# Indexing dari index yang tidak berurutan 
    # dengan menggunakan fancy indexing
# Fancy indexing dicirikan oleh double square brackets
# Urutan elemen yang mau di-indexing bebas
# Tidak bisa melakukan slicing pada fancy indexing
arr[[2, 5, 10]] 

array([ 200,  500, 1000])

In [ ]:
arr_2d = np.array([[10, 15, 20], [25,30, 35], 
                [40, 45, 50], [55, 60, 65]])
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65]])

In [ ]:
# Indexing baris index 0 dan 2
arr_2d[[0, 2]]

array([[10, 15, 20],
       [40, 45, 50]])

In [21]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

## Conditional Selection

In [ ]:
arr = np.arange(100, 1000, 100)
arr

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [ ]:
# Conditional selection mengembalikan nilai boolean
arr > 500

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
greater_500 = arr > 500
greater_500

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
# Untuk menampilkan angkanya, kita bisa panggil terlebih 
    # dahulu nama variabel awal, lalu diikuti oleh 
    # comparison operation.
# Bisa ditampung ke dalam sebuah variabel atau bisa saja 
    # langsung mendefinisikan comparison operation-nya.
arr[greater_500]

array([600, 700, 800, 900])

In [ ]:
arr[arr > 500]

array([600, 700, 800, 900])

## Arithmetic 1D

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Menambahkan angka 3 pada setiap element di array arr
arr + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
# Mengalikan tiap elemen dengan dirinya sendiri
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Arithmetic 2D

In [ ]:
arr.shape

(11,)

In [ ]:
arr_2d = np.array([[10, 15, 20], [25,30, 35], [40, 45, 50]])
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [ ]:
# Mengalikan setiap elemen pada array 2D dengan angka 2
arr_2d * 2

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [ ]:
# Error, gagal dalam broadcasting karena shape antara 
    # kedua array tidak sama (baik itu dalam baris atau kolom)
arr_2d * arr

ValueError: ignored

In [ ]:
arr_1d = np.arange(0, 3)
arr_1d

array([0, 1, 2])

In [ ]:
# Memiliki 1 baris 3 kolom
arr_1d.shape

(3,)

In [ ]:
# Mengubah shape menjadi 3 baris 1 kolom
arr_1d_transpose = arr_1d.T
arr_1d_transpose.shape

(3,)

In [ ]:
# Bisa dikalikan dengan array 2D dengan shape 3x3
arr_2d * arr_1d

array([[  0,  15,  40],
       [  0,  30,  70],
       [  0,  45, 100]])

In [ ]:
# Bisa dikalikan dengan array 2D dengan shape 3x3
arr_2d * arr_1d_transpose

array([[  0,  15,  40],
       [  0,  30,  70],
       [  0,  45, 100]])

- Operasi antar kolom dengan kolom: samakan jumlah baris array pertama dengan jumlah baris array kedua.
- Operasi antar baris dengan baris: samakan jumlah kolom array pertama dengan jumlah kolom array kedua.

## Functions

In [ ]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Akar kuadrat
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
# Sinous
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
# Log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [ ]:
# Eksponensial
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [ ]:
# Menyelipkan sebuah element pada index tertentu
np.insert(arr, 5, 100)

array([  1,   2,   3,   4,   5, 100,   6,   7,   8,   9,  10])

In [ ]:
arr_2d = np.array([[10, 15, 20], [25,30, 35], [40, 45, 50]])
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [ ]:
# Menambahkan kolom pada 2D array
np.insert(arr_2d, 0, [0, 0, 0], axis=1)

array([[ 0, 10, 15, 20],
       [ 0, 25, 30, 35],
       [ 0, 40, 45, 50]])

In [ ]:
# Menambahkan baris pada 2D array
np.insert(arr_2d, 0, [1, 1, 1], axis=0)

array([[ 1,  1,  1],
       [10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [ ]:
# Mengubah array 2D menjadi 1D sekaligus menambahkan 
    # nilai baru pada index baris 0.
# Default-nya axis = None
np.insert(arr_2d, 0, [1, 1, 1])

array([ 1,  1,  1, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# Menghapus element pada index tertentu
np.delete(arr, 2) # Menghapus element index kedua

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Menambahkan elemen pada index terakhir
np.append(arr, 1000)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10, 1000])

In [ ]:
# Menggabungkan 2 array terpisah menjadi 1 array

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10, 20, 30]])

np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [ ]:
b.shape

(1, 3)

In [ ]:
# Transpose array dengan menggunakan .T 
# Baris jadi kolom, kolom jadi baris
np.concatenate((a.T, b.T), axis=1)

array([[ 1,  4, 10],
       [ 2,  5, 20],
       [ 3,  6, 30]])

In [ ]:
# Mengubah element pada index yang kondisinya 
    # True dengan nilai baru
np.where(arr > 3, 99, arr)

array([ 1,  2,  3, 99, 99, 99, 99, 99, 99, 99])

In [ ]:
# Pada 2D array
np.where(arr_2d <= 15, 100, arr_2d)

array([[100, 100,  20],
       [ 25,  30,  35],
       [ 40,  45,  50]])