`June 2, 2022`

# Numpy Exercise

In [ ]:
import numpy as np

**1.**

Buatlah sebuah array 1 dimensi (vektor) yang diisi dengan 36 elemen. Isi dari array tersebut adalah bilangan random dari rentang nilai 1 hingga 100.

Simpan array tersebut dalam sebuah variable bernama my_array, kemudian coba
tampilkan!

In [ ]:
# Insert your code here
my_array = np.random.randint(1, 100, 36)
my_array

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2, 77, 72,  7, 26, 51, 21, 19,
       85, 12, 29, 30, 15, 51, 69, 88, 88, 95, 97, 87, 14, 10,  8, 64, 62,
       23, 58])

**2.**

Dari my_array, bentuklah 3 array dengan bentuk yang berbeda-beda (mengganti dimensi array-nya).

- Array berukuran 2 x 18
- Array berukuran 9 x 4
- Array 3 Dimensi berukuran 2 x 6 x 3

In [ ]:
# Insert your code here
array1 = my_array.reshape(2, 18)
array2 = my_array.reshape(9, 4)
array3 = my_array.reshape(2, 6, 3)

print('Array1\n', array1)
print('\nArray2\n', array2)
print('\nArray3\n', array3)


Array1
 [[38 13 73 10 76  6 80 65 17  2 77 72  7 26 51 21 19 85]
 [12 29 30 15 51 69 88 88 95 97 87 14 10  8 64 62 23 58]]

Array2
 [[38 13 73 10]
 [76  6 80 65]
 [17  2 77 72]
 [ 7 26 51 21]
 [19 85 12 29]
 [30 15 51 69]
 [88 88 95 97]
 [87 14 10  8]
 [64 62 23 58]]

Array3
 [[[38 13 73]
  [10 76  6]
  [80 65 17]
  [ 2 77 72]
  [ 7 26 51]
  [21 19 85]]

 [[12 29 30]
  [15 51 69]
  [88 88 95]
  [97 87 14]
  [10  8 64]
  [62 23 58]]]


**3.**

Berapakah nilai minimun dan maksimum dari my_array? Tampilkan dan coba perlihatkan nilai maksimum dan minimum tersebut ada pada indeks ke berapa!


In [ ]:
# Insert your code here
min_value = my_array.min()
max_value = my_array.max()

min_value_index = my_array.argmin()
max_value_index = my_array.argmax()

print(min_value)
print(max_value)
print(min_value_index)
print(max_value_index)

2
97
9
27


**4.**

Buatlah sebuah array baru dari my_array dengan data yang diambil berasal dari index 3, 5, 30, 12, 15, 8, 24, 14, 22. 

Setelah itu, reshape bentuknya menjadi sebuah array berukuran 3 x 3!

In [ ]:
# Insert your code here

# Gunakan fancy indexing
my_new_array = my_array[[3, 5, 30, 12, 15, 8, 24, 14, 22]]
my_new_array

array([10,  6, 10,  7, 21, 17, 88, 51, 51])

In [ ]:
# Reshape 3x3
my_new_array.reshape(3, 3)

array([[10,  6, 10],
       [ 7, 21, 17],
       [88, 51, 51]])

**5.**

Dari array yang dibuat pada nomor 4, tampilkan data yang nilainya lebih besar dari 50!

In [ ]:
# Insert your code here
my_new_array[my_new_array > 50]

array([88, 51, 51])

**6.**

6. Buat sebuah array menggunkan salah satu method di numpy dengan output seperti di bawah ini!

- Output:
      array([150., 180., 210., 240., 270., 300.])


In [ ]:
# Insert your code here
arr = np.linspace(150, 300, 6, dtype=np.int32)
arr

array([150, 180, 210, 240, 270, 300], dtype=int32)

**7.**

Buatlah sebuah array 2 dimensi dengan ukuran n x n di mana n nya adalah sebuah
inputan. Isi dari array tersebut seluruhnya adalah angka 8!

- Contoh output:
       n yang diinputkan adalah 10
       
       array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
              [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
# Insert your code here

n = int(input('Masukkan nilai n: '))
print(f'\nn yang dimasukkan adalah {n}')

arr8 = np.ones((n, n)) * 8
arr8

Masukkan nilai n: 8

n yang dimasukkan adalah 8


array([[8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.]])

**8.**

Buatlah 2 buah array 2 dimensi seperti di bawah ini, lalu simpan dalam variabel bernama array1 dan array2!

- Output:
        array1
        array([[ 1,  2,  3,  4],
               [ 5,  6,  7,  8],
               [ 9, 10, 11, 12]])

        array2
        array([[100],
               [200],
               [300],
               [400]])


Lalu buatlah sebuah array yang berasal dari gabungan array1 dan array2 seperti di bawah ini, simpan dalam variabel bernama array_merged!

- Output:
        array_merged
        array([[  1,   2,   3,   4],
               [  5,   6,   7,   8],
               [  9,  10,  11,  12],
               [100, 200, 300, 400]])

In [ ]:
# Insert your code here
array1 = np.arange(1, 13).reshape(3, 4)
array2 = np.arange(100, 401, 100).reshape(4, 1)

print(array1)
print()
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[100]
 [200]
 [300]
 [400]]


In [ ]:
# Array merged
array_merged = np.concatenate((array1, array2.T), axis=0)
array_merged

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

**9.**

Dari array_merged, lakukan slicing agar menghasilkan array di bawah ini!

- Output:
      array([[ 7,  8],
             [11, 12]])


In [ ]:
# Insert your code here
array_merged[1:3, 2:]

array([[ 7,  8],
       [11, 12]])

**10.**

Dari array_merged, lakukan indexing untuk mendapatkan angka 200!

In [ ]:
# Insert your code here
array_merged[3, 1]

200

**11.**

Dari 2 array berikut, tampilkan index yang nilainya sama antara array a dan b.

    a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
    b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])


- Output:
        array([1, 3, 5, 7])

In [ ]:
# Insert your code here
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

np.where(a == b)

(array([1, 3, 5, 7]),)

**12.**

Dari array berikut, tampilkan nilai yang range-nya antara 5 dan 10!

      x = np.array([2, 6, 1, 9, 10, 3, 27])

- Output:
      array([6, 9, 10])

In [ ]:
# Insert your code here
x = np.array([2, 6, 1, 9, 10, 3, 27])

filtered = np.where((x >= 5) & (x <= 10))
print(filtered) # by default akan mengembalikan nilai index

print(x[filtered])

(array([1, 3, 4]),)
[ 6  9 10]


**13.**

Jika kode berikut dijalankan:

      arr = np.arange(9).reshape(3, 3)

Outputnya adalah:

      array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])


Bagaimana mengubah output di atas menjadi seperti berikut?

Output: 
 
      array([[1, 0, 2],
             [4, 3, 5],
             [7, 6, 8]])

In [ ]:
# Insert your code here
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Ubah posisi
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

**14.** 

Jika kode berikut dijalankan --> arr = np.arange(9).reshape(3, 3) outputnya adalah:

        array([[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]])

 Bagaimana mengubah output di atas menjadi seperti berikut?

 Output:

        array([[3, 4, 5],
               [0, 1, 2],
               [6, 7, 8]])

In [ ]:
# Insert your code here
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Ubah posisi
arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

**15.**

Jika kode berikut dijalankan --> arr = np.arange(9).reshape(3, 3) outputnya adalah:

      array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

Bagaimana mengubah output di atas menjadi seperti berikut?

Output:

      array([[2, 1, 0],
             [5, 4, 3],
             [8, 7, 6]])

In [ ]:
# Insert your code here
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Ubah posisi
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])